// AUTO-GENERATED from SPT 4.1 EFT player.bundle (PlayerBody.SkeletonHands Skeleton._keys).
// Paths are relative to Root_Joint. Body/feet/head Skins use "Root_Joint/" + path; hands Skins use the path as-is
// (PlayerBody.SetSkin passes SkeletonHands for EBodyModelPart.Hands, SkeletonRootJoint otherwise).
// Leaf names that occur twice in the skeleton (XYZ, XYZ_1) are omitted because a name lookup would be ambiguous.
namespace EFTAutoPrefab
{
    public static class EFTSkeletonData
    {
        // 120 entries
        public static readonly string[] RootJointRelativePaths =
        {
            "Base HumanPelvis",
            "Base HumanPelvis/Base HumanLThigh1",
            "Base HumanPelvis/Base HumanLThigh1/Base HumanLThigh2",
            "Base HumanPelvis/Base HumanLThigh1/Base HumanLThigh2/Base HumanLCalf",
            "Base HumanPelvis/Base HumanLThigh1/Base HumanLThigh2/Base HumanLCalf/Base HumanLFoot",
            "Base HumanPelvis/Base HumanLThigh1/Base HumanLThigh2/Base HumanLCalf/Base HumanLFoot/Base HumanLToe",
            "Base HumanPelvis/Base HumanRThigh1",
            "Base HumanPelvis/Base HumanRThigh1/BEAR_feet_1",
            "Base HumanPelvis/Base HumanRThigh1/Base HumanRThigh2",
            "Base HumanPelvis/Base HumanRThigh1/Base HumanRThigh2/Base HumanRCalf",
            "Base HumanPelvis/Base HumanRThigh1/Base HumanRThigh2/Base HumanRCalf/Base HumanRFoot",
            "Base HumanPelvis/Base HumanRThigh1/Base HumanRThigh2/Base HumanRCalf/Base HumanRFoot/Base HumanRToe",
            "Base HumanPelvis/Base HumanRThigh1/Bear_Feet",
            "Base HumanPelvis/Base HumanRThigh1/USEC_Feet",
            "Base HumanPelvis/Base HumanRThigh1/weapon_holster_pistol",
            "Base HumanPelvis/Base HumanSpine1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanGear1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanGear2",
            "Base HumanPelvis/Base HumanSpine1/Base HumanGear3",
            "Base HumanPelvis/Base HumanSpine1/Base HumanGear4",
            "Base HumanPelvis/Base HumanSpine1/Base HumanGear4/Base HumanGear4_1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanGear5",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanBackpack",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit11",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit11/Base HumanLDigit12",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit11/Base HumanLDigit12/Base HumanLDigit13",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit21",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit21/Base HumanLDigit22",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit21/Base HumanLDigit22/Base HumanLDigit23",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit31",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit31/Base HumanLDigit32",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit31/Base HumanLDigit32/Base HumanLDigit33",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit41",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit41/Base HumanLDigit42",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit41/Base HumanLDigit42/Base HumanLDigit43",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit51",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit51/Base HumanLDigit52",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanLCollarbone/Base HumanLUpperarm/Base HumanLForearm1/Base HumanLForearm2/Base HumanLForearm3/Base HumanLPalm/Base HumanLDigit51/Base HumanLDigit52/Base HumanLDigit53",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit11",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit11/Base HumanRDigit12",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit11/Base HumanRDigit12/Base HumanRDigit13",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit21",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit21/Base HumanRDigit22",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit21/Base HumanRDigit22/Base HumanRDigit23",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit31",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit31/Base HumanRDigit32",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit31/Base HumanRDigit32/Base HumanRDigit33",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit41",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit41/Base HumanRDigit42",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit41/Base HumanRDigit42/Base HumanRDigit43",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit51",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit51/Base HumanRDigit52",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Base HumanRCollarbone/Base HumanRUpperarm/Base HumanRForearm1/Base HumanRForearm2/Base HumanRForearm3/Base HumanRPalm/Base HumanRDigit51/Base HumanRDigit52/Base HumanRDigit53",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/CameraContainer",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/CameraContainer/Cam",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Camera_animated",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit11",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit11/IK_LDigit12",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit11/IK_LDigit12/IK_LDigit13",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit21",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit21/IK_LDigit22",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit21/IK_LDigit22/IK_LDigit23",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit31",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit31/IK_LDigit32",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit31/IK_LDigit32/IK_LDigit33",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit41",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit41/IK_LDigit42",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit41/IK_LDigit42/IK_LDigit43",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit51",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit51/IK_LDigit52",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/IK_LForearm1/IK_LForearm2/IK_LForearm3/IK_LPalm/IK_LDigit51/IK_LDigit52/IK_LDigit53",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanRibcage/Weapon_root",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Bend_Goal_Left",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Bend_Goal_Right",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit11",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit11/IK_S_LDigit12",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit11/IK_S_LDigit12/IK_S_LDigit13",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit21",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit21/IK_S_LDigit22",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit21/IK_S_LDigit22/IK_S_LDigit23",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit31",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit31/IK_S_LDigit32",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit31/IK_S_LDigit32/IK_S_LDigit33",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit41",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit41/IK_S_LDigit42",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit41/IK_S_LDigit42/IK_S_LDigit43",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit51",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit51/IK_S_LDigit52",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/IK_S_LForearm1/IK_S_LForearm2/IK_S_LForearm3/IK_S_LPalm/IK_S_LDigit51/IK_S_LDigit52/IK_S_LDigit53",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/LCollarbone_anim",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/RCollarbone_anim",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Weapon_root_3rd_anim",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/weapon_holster",
            "Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/weapon_holster1",
            "Camera_animated_3rd",
        };
    }
}
