/*
* Autodesk Maya Bind Script
* Exported by PorterLib
*/

global proc PorterMesh_ffa7c186_0_BindFunc()
{
	select -r PorterMesh_ffa7c186_0;
	select -add tag_accessory;
	newSkinCluster "-toSelectedBones -mi 8 -omi true -dr 5.0 -rui false";
	string $clu = findRelatedSkinCluster("PorterMesh_ffa7c186_0");
}

global proc PorterMesh_ffa7c186_1_BindFunc()
{
	select -r PorterMesh_ffa7c186_1;
	select -add tag_accessory;
	newSkinCluster "-toSelectedBones -mi 8 -omi true -dr 5.0 -rui false";
	string $clu = findRelatedSkinCluster("PorterMesh_ffa7c186_1");
}

global proc PorterMesh_ffa7c186_2_BindFunc()
{
	select -r PorterMesh_ffa7c186_2;
	select -add tag_accessory;
	newSkinCluster "-toSelectedBones -mi 8 -omi true -dr 5.0 -rui false";
	string $clu = findRelatedSkinCluster("PorterMesh_ffa7c186_2");
}

global proc PorterMesh_ffa7c186_3_BindFunc()
{
	select -r PorterMesh_ffa7c186_3;
	select -add tag_accessory;
	newSkinCluster "-toSelectedBones -mi 8 -omi true -dr 5.0 -rui false";
	string $clu = findRelatedSkinCluster("PorterMesh_ffa7c186_3");
}

global proc RunAdvancedScript()
{
	catch(PorterMesh_ffa7c186_0_BindFunc());
	catch(PorterMesh_ffa7c186_1_BindFunc());
	catch(PorterMesh_ffa7c186_2_BindFunc());
	catch(PorterMesh_ffa7c186_3_BindFunc());
}

global proc NamespacePurge()
{
	string $allNodes[] = `ls`;
	for($node in $allNodes) {
		string $buffer[];
		tokenize $node ":" $buffer;
		string $newName = $buffer[size($buffer)-1];
		catchQuiet(`rename $node $newName`);
	}
}

print("Currently binding the current model, please wait...\n");
NamespacePurge();
RunAdvancedScript();
print("The model has been binded.\n");
